######################################################################
# Automatically generated by qmake (3.0) ? 11 16 11:54:38 2013
######################################################################

TEMPLATE = app
TARGET = qtsample_03
INCLUDEPATH += . src

# Input
HEADERS += src/Tetrahedron.h
SOURCES += src/main.cpp src/Tetrahedron.cpp

QT += opengl
win32:INCLUDEPATH += C:/lib/glew/include
win32:LIBS += C:/lib/glew/lib/libglew32.dll.a
