######################################################################
# Automatically generated by qmake (2.01a) ? 5? 19 16:20:36 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += qt debug

# Input
HEADERS += common.h
SOURCES += main.cpp
