######################################################################
# Automatically generated by qmake (3.0) ? 11 10 10:33:00 2013
######################################################################


TEMPLATE = app
TARGET = qtsample_01
INCLUDEPATH += .

# Input
HEADERS += src/MainWindow.h\
           src/ProjectListWidget.h
SOURCES += src/main.cpp\
           src/MainWindow.cpp\
           src/ProjectListWidget.cpp

QT += opengl
RESOURCES = resources.qrc
