######################################################################
# Automatically generated by qmake (3.0) ? 11 10 10:40:19 2013
######################################################################

TEMPLATE = app
TARGET = qtskeleton
INCLUDEPATH += .

# Input
SOURCES += src/main.cpp
QT += core gui opengl
