######################################################################
# Automatically generated by qmake (3.0) ? 11 15 08:05:12 2013
######################################################################

TEMPLATE = app
TARGET = qtsample_02
INCLUDEPATH += . src

# Input
HEADERS += src/HexSpinBox.h\
           src/IconEditor/IconEditor.h
FORMS += src/HexSpinBox.ui
SOURCES += src/HexSpinBox.cpp src/main.cpp src/IconEditor/IconEditor.cpp
QT += opengl
RESOURCES = resources.qrc
